# Generated by Django 3.0.6 on 2020-07-12 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20200711_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherinfo',
            old_name='user_name',
            new_name='user',
        ),
    ]
