# Generated by Django 3.0.6 on 2020-08-01 14:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_attendence'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherinfo',
            name='due',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='salarypay_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Teacher_Payment_Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_payer_name', models.CharField(max_length=100)),
                ('paid_amount', models.IntegerField()),
                ('due_amount', models.IntegerField()),
                ('paid_date', models.DateField(default=django.utils.timezone.now)),
                ('teacherinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacherinfo')),
            ],
        ),
    ]
