# Generated by Django 3.0.6 on 2020-08-08 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staffinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=100)),
                ('salary', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('date_join', models.DateField()),
                ('living_address', models.CharField(max_length=100)),
                ('introduction', models.TextField(blank=True, null=True)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('salarypay_date', models.DateField(blank=True, null=True)),
                ('due', models.IntegerField(blank=True, default=0, null=True)),
                ('type_of_staff', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Payment_Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_payer_name', models.CharField(max_length=100)),
                ('paid_amount', models.IntegerField()),
                ('due_amount', models.IntegerField()),
                ('paid_date', models.DateField(default=django.utils.timezone.now)),
                ('staffinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Staffinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendence', models.CharField(choices=[('A', 'A'), ('P', 'P')], max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('staffinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Staffinfo')),
            ],
        ),
    ]
