# Generated by Django 3.0.6 on 2020-08-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffinfo',
            name='subject',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
