# Generated by Django 3.0.6 on 2020-07-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='due',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='feepay_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
