# Generated by Django 3.0.6 on 2020-07-27 01:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200726_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Payment_Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_payer_name', models.CharField(max_length=100)),
                ('paid_amount', models.IntegerField()),
                ('due_amount', models.IntegerField()),
                ('paid_date', models.DateField(default=django.utils.timezone.now)),
                ('studentinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Studentinfo')),
            ],
        ),
    ]
