# Generated by Django 3.0.6 on 2020-07-28 02:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_payment_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendence', models.CharField(choices=[('A', 'A'), ('P', 'P')], max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('studentinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Studentinfo')),
            ],
        ),
    ]
